spring:
  application:
    name: microservice-two
server:
  servlet:
    context-path: /service-two
  port: 8662 
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true 
    hostname: ${COMPUTERNAME}
      
